### ISSUE TITLE
Error Message: "Adapter RootElement, "assets", is not a valid path for the response JSON."

### ISSUE THREAD

**Issue by Mabinogiysk** [exercism/windows-installer#38] opened 2018-05-29 03:56 UTC
I got an error during installing:
```
Adapter RootElement, "assets", is not a valid path for the response JSON.
```
![image](https://user-images.githubusercontent.com/12441989/40637408-48095098-6337-11e8-86ac-ad5056d3c947.png)

**Comment by rpottsoh** [comment] 2018-05-29 13:27
@Mabinogiysk thanks for bringing  this issue to my attention.  How many times have you tried to run the installer?  I want to make sure that you have tried more than once.  Did you you just recently download the installer?  I want to make sure you are using the [latest](https://github.com/exercism/windows-installer/releases/latest) version of the installer.

So far, I am unable to reproduce this error.  Please copy & paste this url:
`https://api.github.com/repos/exercism/cli/releases/latest`
into new web browser window and then copy and paste the response you receive in that browser window as a new comment to this issue.

**Comment by Mabinogiysk** [comment] 2018-05-30 02:43
I was using the latest version 1.4.3 and I had tried it for several times. Now I have installed it with manual installation.
I am using win7 enterprise, which is customized by the company. I think this is the problem, but I do not know what the locale settings is.
I have tried the latest version 1.4.4 and the problem remains the same. Never mind, now I can use it without any problems.

**Comment by rpottsoh** [comment] 2018-05-30 13:48
@Mabinogiysk I am glad to see that you were able to install the CLI manually.  Before I put this issue to bed would you mind posting here, from the browser of the computer that is causing the problem, the output from `https://api.github.com/repos/exercism/cli/releases/latest`.  I would like a chance to examine the response to see what may be unexpectedly different.

**Comment by Mabinogiysk** [comment] 2018-05-31 01:11
{
  "url": "https://api.github.com/repos/exercism/cli/releases/6902445",
  "assets_url": "https://api.github.com/repos/exercism/cli/releases/6902445/assets",
  "upload_url": "https://uploads.github.com/repos/exercism/cli/releases/6902445/assets{?name,label}",
  "html_url": "https://github.com/exercism/cli/releases/tag/v2.4.1",
  "id": 6902445,
  "node_id": "MDc6UmVsZWFzZTY5MDI0NDU=",
  "tag_name": "v2.4.1",
  "target_commitish": "3968e887bae5e6ff32e1f29f19e5830c9721da44",
  "name": "Fix upgrade command on Windows",
  "draft": false,
  "author": {
    "login": "kytrinyx",
    "id": 276834,
    "node_id": "MDQ6VXNlcjI3NjgzNA==",
    "avatar_url": "https://avatars1.githubusercontent.com/u/276834?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/kytrinyx",
    "html_url": "https://github.com/kytrinyx",
    "followers_url": "https://api.github.com/users/kytrinyx/followers",
    "following_url": "https://api.github.com/users/kytrinyx/following{/other_user}",
    "gists_url": "https://api.github.com/users/kytrinyx/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/kytrinyx/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/kytrinyx/subscriptions",
    "organizations_url": "https://api.github.com/users/kytrinyx/orgs",
    "repos_url": "https://api.github.com/users/kytrinyx/repos",
    "events_url": "https://api.github.com/users/kytrinyx/events{/privacy}",
    "received_events_url": "https://api.github.com/users/kytrinyx/received_events",
    "type": "User",
    "site_admin": true
  },
  "prerelease": false,
  "created_at": "2017-07-01T18:45:36Z",
  "published_at": "2017-07-01T18:51:44Z",
  "assets": [
    {
      "url": "https://api.github.com/repos/exercism/cli/releases/assets/4232613",
      "id": 4232613,
      "node_id": "MDEyOlJlbGVhc2VBc3NldDQyMzI2MTM=",
      "name": "exercism-linux-32bit.tgz",
      "label": null,
      "uploader": {
        "login": "kytrinyx",
        "id": 276834,
        "node_id": "MDQ6VXNlcjI3NjgzNA==",
        "avatar_url": "https://avatars1.githubusercontent.com/u/276834?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/kytrinyx",
        "html_url": "https://github.com/kytrinyx",
        "followers_url": "https://api.github.com/users/kytrinyx/followers",
        "following_url": "https://api.github.com/users/kytrinyx/following{/other_user}",
        "gists_url": "https://api.github.com/users/kytrinyx/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/kytrinyx/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/kytrinyx/subscriptions",
        "organizations_url": "https://api.github.com/users/kytrinyx/orgs",
        "repos_url": "https://api.github.com/users/kytrinyx/repos",
        "events_url": "https://api.github.com/users/kytrinyx/events{/privacy}",
        "received_events_url": "https://api.github.com/users/kytrinyx/received_events",
        "type": "User",
        "site_admin": true
      },
      "content_type": "application/gzip",
      "state": "uploaded",
      "size": 3170627,
      "download_count": 676,
      "created_at": "2017-07-01T18:50:46Z",
      "updated_at": "2017-07-01T18:50:52Z",
      "browser_download_url": "https://github.com/exercism/cli/releases/download/v2.4.1/exercism-linux-32bit.tgz"
    },
    {
      "url": "https://api.github.com/repos/exercism/cli/releases/assets/4232614",
      "id": 4232614,
      "node_id": "MDEyOlJlbGVhc2VBc3NldDQyMzI2MTQ=",
      "name": "exercism-linux-64bit.tgz",
      "label": null,
      "uploader": {
        "login": "kytrinyx",
        "id": 276834,
        "node_id": "MDQ6VXNlcjI3NjgzNA==",
        "avatar_url": "https://avatars1.githubusercontent.com/u/276834?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/kytrinyx",
        "html_url": "https://github.com/kytrinyx",
        "followers_url": "https://api.github.com/users/kytrinyx/followers",
        "following_url": "https://api.github.com/users/kytrinyx/following{/other_user}",
        "gists_url": "https://api.github.com/users/kytrinyx/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/kytrinyx/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/kytrinyx/subscriptions",
        "organizations_url": "https://api.github.com/users/kytrinyx/orgs",
        "repos_url": "https://api.github.com/users/kytrinyx/repos",
        "events_url": "https://api.github.com/users/kytrinyx/events{/privacy}",
        "received_events_url": "https://api.github.com/users/kytrinyx/received_events",
        "type": "User",
        "site_admin": true
      },
      "content_type": "application/gzip",
      "state": "uploaded",
      "size": 3356261,
      "download_count": 353172,
      "created_at": "2017-07-01T18:50:47Z",
      "updated_at": "2017-07-01T18:50:57Z",
      "browser_download_url": "https://github.com/exercism/cli/releases/download/v2.4.1/exercism-linux-64bit.tgz"
    },
    {
      "url": "https://api.github.com/repos/exercism/cli/releases/assets/4232618",
      "id": 4232618,
      "node_id": "MDEyOlJlbGVhc2VBc3NldDQyMzI2MTg=",
      "name": "exercism-linux-arm-v5.tgz",
      "label": null,
      "uploader": {
        "login": "kytrinyx",
        "id": 276834,
        "node_id": "MDQ6VXNlcjI3NjgzNA==",
        "avatar_url": "https://avatars1.githubusercontent.com/u/276834?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/kytrinyx",
        "html_url": "https://github.com/kytrinyx",
        "followers_url": "https://api.github.com/users/kytrinyx/followers",
        "following_url": "https://api.github.com/users/kytrinyx/following{/other_user}",
        "gists_url": "https://api.github.com/users/kytrinyx/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/kytrinyx/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/kytrinyx/subscriptions",
        "organizations_url": "https://api.github.com/users/kytrinyx/orgs",
        "repos_url": "https://api.github.com/users/kytrinyx/repos",
        "events_url": "https://api.github.com/users/kytrinyx/events{/privacy}",
        "received_events_url": "https://api.github.com/users/kytrinyx/received_events",
        "type": "User",
        "site_admin": true
      },
      "content_type": "application/gzip",
      "state": "uploaded",
      "size": 3163896,
      "download_count": 31,
      "created_at": "2017-07-01T18:50:47Z",
      "updated_at": "2017-07-01T18:51:15Z",
      "browser_download_url": "https://github.com/exercism/cli/releases/download/v2.4.1/exercism-linux-arm-v5.tgz"
    },
    {
      "url": "https://api.github.com/repos/exercism/cli/releases/assets/4232615",
      "id": 4232615,
      "node_id": "MDEyOlJlbGVhc2VBc3NldDQyMzI2MTU=",
      "name": "exercism-linux-arm-v6.tgz",
      "label": null,
      "uploader": {
        "login": "kytrinyx",
        "id": 276834,
        "node_id": "MDQ6VXNlcjI3NjgzNA==",
        "avatar_url": "https://avatars1.githubusercontent.com/u/276834?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/kytrinyx",
        "html_url": "https://github.com/kytrinyx",
        "followers_url": "https://api.github.com/users/kytrinyx/followers",
        "following_url": "https://api.github.com/users/kytrinyx/following{/other_user}",
        "gists_url": "https://api.github.com/users/kytrinyx/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/kytrinyx/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/kytrinyx/subscriptions",
        "organizations_url": "https://api.github.com/users/kytrinyx/orgs",
        "repos_url": "https://api.github.com/users/kytrinyx/repos",
        "events_url": "https://api.github.com/users/kytrinyx/events{/privacy}",
        "received_events_url": "https://api.github.com/users/kytrinyx/received_events",
        "type": "User",
        "site_admin": true
      },
      "content_type": "application/gzip",
      "state": "uploaded",
      "size": 3143965,
      "download_count": 26,
      "created_at": "2017-07-01T18:50:47Z",
      "updated_at": "2017-07-01T18:51:01Z",
      "browser_download_url": "https://github.com/exercism/cli/releases/download/v2.4.1/exercism-linux-arm-v6.tgz"
    },
    {
      "url": "https://api.github.com/repos/exercism/cli/releases/assets/4232617",
      "id": 4232617,
      "node_id": "MDEyOlJlbGVhc2VBc3NldDQyMzI2MTc=",
      "name": "exercism-linux-arm-v7.tgz",
      "label": null,
      "uploader": {
        "login": "kytrinyx",
        "id": 276834,
        "node_id": "MDQ6VXNlcjI3NjgzNA==",
        "avatar_url": "https://avatars1.githubusercontent.com/u/276834?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/kytrinyx",
        "html_url": "https://github.com/kytrinyx",
        "followers_url": "https://api.github.com/users/kytrinyx/followers",
        "following_url": "https://api.github.com/users/kytrinyx/following{/other_user}",
        "gists_url": "https://api.github.com/users/kytrinyx/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/kytrinyx/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/kytrinyx/subscriptions",
        "organizations_url": "https://api.github.com/users/kytrinyx/orgs",
        "repos_url": "https://api.github.com/users/kytrinyx/repos",
        "events_url": "https://api.github.com/users/kytrinyx/events{/privacy}",
        "received_events_url": "https://api.github.com/users/kytrinyx/received_events",
        "type": "User",
        "site_admin": true
      },
      "content_type": "application/gzip",
      "state": "uploaded",
      "size": 3142804,
      "download_count": 167,
      "created_at": "2017-07-01T18:50:47Z",
      "updated_at": "2017-07-01T18:51:06Z",
      "browser_download_url": "https://github.com/exercism/cli/releases/download/v2.4.1/exercism-linux-arm-v7.tgz"
    },
    {
      "url": "https://api.github.com/repos/exercism/cli/releases/assets/4232616",
      "id": 4232616,
      "node_id": "MDEyOlJlbGVhc2VBc3NldDQyMzI2MTY=",
      "name": "exercism-linux-arm-v8.tgz",
      "label": null,
      "uploader": {
        "login": "kytrinyx",
        "id": 276834,
        "node_id": "MDQ6VXNlcjI3NjgzNA==",
        "avatar_url": "https://avatars1.githubusercontent.com/u/276834?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/kytrinyx",
        "html_url": "https://github.com/kytrinyx",
        "followers_url": "https://api.github.com/users/kytrinyx/followers",
        "following_url": "https://api.github.com/users/kytrinyx/following{/other_user}",
        "gists_url": "https://api.github.com/users/kytrinyx/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/kytrinyx/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/kytrinyx/subscriptions",
        "organizations_url": "https://api.github.com/users/kytrinyx/orgs",
        "repos_url": "https://api.github.com/users/kytrinyx/repos",
        "events_url": "https://api.github.com/users/kytrinyx/events{/privacy}",
        "received_events_url": "https://api.github.com/users/kytrinyx/received_events",
        "type": "User",
        "site_admin": true
      },
      "content_type": "application/gzip",
      "state": "uploaded",
      "size": 3102124,
      "download_count": 151,
      "created_at": "2017-07-01T18:50:47Z",
      "updated_at": "2017-07-01T18:51:10Z",
      "browser_download_url": "https://github.com/exercism/cli/releases/download/v2.4.1/exercism-linux-arm-v8.tgz"
    },
    {
      "url": "https://api.github.com/repos/exercism/cli/releases/assets/4232619",
      "id": 4232619,
      "node_id": "MDEyOlJlbGVhc2VBc3NldDQyMzI2MTk=",
      "name": "exercism-mac-32bit.tgz",
      "label": null,
      "uploader": {
        "login": "kytrinyx",
        "id": 276834,
        "node_id": "MDQ6VXNlcjI3NjgzNA==",
        "avatar_url": "https://avatars1.githubusercontent.com/u/276834?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/kytrinyx",
        "html_url": "https://github.com/kytrinyx",
        "followers_url": "https://api.github.com/users/kytrinyx/followers",
        "following_url": "https://api.github.com/users/kytrinyx/following{/other_user}",
        "gists_url": "https://api.github.com/users/kytrinyx/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/kytrinyx/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/kytrinyx/subscriptions",
        "organizations_url": "https://api.github.com/users/kytrinyx/orgs",
        "repos_url": "https://api.github.com/users/kytrinyx/repos",
        "events_url": "https://api.github.com/users/kytrinyx/events{/privacy}",
        "received_events_url": "https://api.github.com/users/kytrinyx/received_events",
        "type": "User",
        "site_admin": true
      },
      "content_type": "application/gzip",
      "state": "uploaded",
      "size": 3161204,
      "download_count": 23,
      "created_at": "2017-07-01T18:50:47Z",
      "updated_at": "2017-07-01T18:51:19Z",
      "browser_download_url": "https://github.com/exercism/cli/releases/download/v2.4.1/exercism-mac-32bit.tgz"
    },
    {
      "url": "https://api.github.com/repos/exercism/cli/releases/assets/4232620",
      "id": 4232620,
      "node_id": "MDEyOlJlbGVhc2VBc3NldDQyMzI2MjA=",
      "name": "exercism-mac-64bit.tgz",
      "label": null,
      "uploader": {
        "login": "kytrinyx",
        "id": 276834,
        "node_id": "MDQ6VXNlcjI3NjgzNA==",
        "avatar_url": "https://avatars1.githubusercontent.com/u/276834?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/kytrinyx",
        "html_url": "https://github.com/kytrinyx",
        "followers_url": "https://api.github.com/users/kytrinyx/followers",
        "following_url": "https://api.github.com/users/kytrinyx/following{/other_user}",
        "gists_url": "https://api.github.com/users/kytrinyx/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/kytrinyx/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/kytrinyx/subscriptions",
        "organizations_url": "https://api.github.com/users/kytrinyx/orgs",
        "repos_url": "https://api.github.com/users/kytrinyx/repos",
        "events_url": "https://api.github.com/users/kytrinyx/events{/privacy}",
        "received_events_url": "https://api.github.com/users/kytrinyx/received_events",
        "type": "User",
        "site_admin": true
      },
      "content_type": "application/gzip",
      "state": "uploaded",
      "size": 3343497,
      "download_count": 1341,
      "created_at": "2017-07-01T18:50:47Z",
      "updated_at": "2017-07-01T18:51:24Z",
      "browser_download_url": "https://github.com/exercism/cli/releases/download/v2.4.1/exercism-mac-64bit.tgz"
    },
    {
      "url": "https://api.github.com/repos/exercism/cli/releases/assets/4232621",
      "id": 4232621,
      "node_id": "MDEyOlJlbGVhc2VBc3NldDQyMzI2MjE=",
      "name": "exercism-windows-32bit.zip",
      "label": null,
      "uploader": {
        "login": "kytrinyx",
        "id": 276834,
        "node_id": "MDQ6VXNlcjI3NjgzNA==",
        "avatar_url": "https://avatars1.githubusercontent.com/u/276834?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/kytrinyx",
        "html_url": "https://github.com/kytrinyx",
        "followers_url": "https://api.github.com/users/kytrinyx/followers",
        "following_url": "https://api.github.com/users/kytrinyx/following{/other_user}",
        "gists_url": "https://api.github.com/users/kytrinyx/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/kytrinyx/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/kytrinyx/subscriptions",
        "organizations_url": "https://api.github.com/users/kytrinyx/orgs",
        "repos_url": "https://api.github.com/users/kytrinyx/repos",
        "events_url": "https://api.github.com/users/kytrinyx/events{/privacy}",
        "received_events_url": "https://api.github.com/users/kytrinyx/received_events",
        "type": "User",
        "site_admin": true
      },
      "content_type": "application/zip",
      "state": "uploaded",
      "size": 3153780,
      "download_count": 1129,
      "created_at": "2017-07-01T18:50:47Z",
      "updated_at": "2017-07-01T18:51:29Z",
      "browser_download_url": "https://github.com/exercism/cli/releases/download/v2.4.1/exercism-windows-32bit.zip"
    },
    {
      "url": "https://api.github.com/repos/exercism/cli/releases/assets/4232622",
      "id": 4232622,
      "node_id": "MDEyOlJlbGVhc2VBc3NldDQyMzI2MjI=",
      "name": "exercism-windows-64bit.zip",
      "label": null,
      "uploader": {
        "login": "kytrinyx",
        "id": 276834,
        "node_id": "MDQ6VXNlcjI3NjgzNA==",
        "avatar_url": "https://avatars1.githubusercontent.com/u/276834?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/kytrinyx",
        "html_url": "https://github.com/kytrinyx",
        "followers_url": "https://api.github.com/users/kytrinyx/followers",
        "following_url": "https://api.github.com/users/kytrinyx/following{/other_user}",
        "gists_url": "https://api.github.com/users/kytrinyx/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/kytrinyx/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/kytrinyx/subscriptions",
        "organizations_url": "https://api.github.com/users/kytrinyx/orgs",
        "repos_url": "https://api.github.com/users/kytrinyx/repos",
        "events_url": "https://api.github.com/users/kytrinyx/events{/privacy}",
        "received_events_url": "https://api.github.com/users/kytrinyx/received_events",
        "type": "User",
        "site_admin": true
      },
      "content_type": "application/zip",
      "state": "uploaded",
      "size": 3342354,
      "download_count": 22032,
      "created_at": "2017-07-01T18:50:47Z",
      "updated_at": "2017-07-01T18:51:33Z",
      "browser_download_url": "https://github.com/exercism/cli/releases/download/v2.4.1/exercism-windows-64bit.zip"
    }
  ],
  "tarball_url": "https://api.github.com/repos/exercism/cli/tarball/v2.4.1",
  "zipball_url": "https://api.github.com/repos/exercism/cli/zipball/v2.4.1",
  "body": "### Exercism Command-Line Interface (CLI)\r\n\r\nExercism takes place in two places: the discussions happen on the website, and you work on exercises locally. The CLI bridges the gap, allowing you to fetch exercises and submit solutions to the site.\r\n\r\nThis is a stand-alone binary, which means that you don't need to install any particular language or environment in order to use it.\r\n\r\nTo install, download the archive that matches your operating system and architecture, unpack the archive, and put the binary somewhere on your path.\r\n\r\nYou will need to configure the CLI with your [Exercism API Key](http://exercism.io/account/key) before submitting.\r\n\r\nFor more detailed instructions, see the [CLI page on Exercism](http://exercism.io/clients/cli).\r\n\r\n#### Recent Changes\r\n\r\n* @Tonkpils fixed the `exercism upgrade` command for Windows! 🎉 \r\n"
}

**Comment by Mabinogiysk** [comment] 2018-05-31 01:32
Thanks for your help, I am glad that I can help you.

**Comment by rpottsoh** [comment] 2018-06-03 23:49
@Mabinogiysk I have been working on a pre-release version that attempts to address the issue you reported a few days ago.  I know you managed to get the CLI installed manually, but I am hoping that you would be willing and able to test this new version.  You are the only that I know that can recreate the problem.  The trial version is available for download from here: https://github.com/rpottsoh/exercism-windows-installer/releases/download/v1.4.4ALPHA/ExercismCLIInstallerALPHA.EXE

Let me know if you have any questions and thanks for your help on this.

**Comment by Mabinogiysk** [comment] 2018-06-04 11:34
I have intalled it with this version!

**Comment by rpottsoh** [comment] 2018-06-04 12:33
Excellent!  Thanks for testing this for me.

**Comment by rpottsoh** [comment] 2018-06-04 12:36
I will close this issue when I release a new version of the installer.

**Closed** 2018-06-05 02:13 UTC
Labels: bug, fixed, not reproducable
